### ISSUE TITLE
NullReferenceException when a new controller is introduced.

### ISSUE THREAD

**Issue by EtimUdo** [rodriguezfa/AdminLTE.NETCore#3]
First of all, I thank you for the Job done so far. I downloaded the theme, installed all the necessary nuget packages and ran the app. Everything runs fine. However, I added a new controller,, build was successful. when i run the application I get the following error:

NullReferenceException: Object reference not set to an instance of an object.
AdminLTE.NETCore.Models.ControllerInformationRepository+<>c.<.ctor>b__1_4(<>f__AnonymousType9<string, string, DisplayImageAttribute, IEnumerable<MethodInfo>, TreeViewAttribute, TreeViewSettingsAttribute> a) in ControllerInformationRepository.cs, line 50

I have tried debugging but still stuck.

**Comment by rodriguezfa** [comment]
Hi,
  I suspect that you didn't setup the attributes on the controller that this module is looking for.

It looks like "DisplayImageAttribute" and "ScriptAfterPartialViewAttribute" are required.

Francisco

**Comment by EtimUdo** [comment]
Awesome... It worked. Thank you
